### ISSUE TITLE
Better input methods

### ISSUE THREAD

**Issue by muehlt** [DevEmperor/WristAssist#12]
Hi,

I know one cannot spend too much time on those hobby projects, but do you find the time to add a simple complication for direct voice input or at least a better method to input spoken text? Currently, you are using a text input, but the best practice would be to have the menu to choose between input methods as in other apps (see [documentation](https://developer.android.com/training/wearables/user-input/wear-ime)). Currently, it's at least 4 clicks to access a new chat and speech input, which is unhandy if used as an assistant, which is the primary purpose since you cannot provide long text for more elaborate tasks.

As a side note, did you have a look at [Assistants API](https://platform.openai.com/docs/assistants/overview)? This could be a powerful tool to have on the wrist.

Cheers!

**Comment by DevEmperor** [comment]
Hey, thanks for drawing attention to this problem. You definitely have a point there, I've already noticed the many clicks and the idea with the complications sounds very promising. I'll make sure that I can implement this in the next few days despite all the current stress. :)

I've heard the news about the Assistants API, but as I said, I haven't had time to find out more about it yet. I'll put that on the top of my to-do list and see if I can integrate something helpful.
I'll keep you up to date. :)

**Comment by muehlt** [comment]
Thanks! Some apps also have separate activities in the app launcher that perform different actions. I think this is because they not only work as complications (App-Shortcuts) but also with customizable buttons that some watches have.

I'm also really interested in the Assistant API, as it enables many devices to access a Langchain-like framework. Although I currently don't really have the time to develop, let me know if you want to brainstorm together on something.

**Comment by DevEmperor** [comment]
Hey,
I've been doing some research over the last few days, but unfortunately I haven't found a way to create a complication in Java. (There was an outdated documentation on the Android developer page, but as I said, it should no longer be used). I'm still working on the feature because I think it makes a lot of sense.
In the meantime, I have at least added a setting that automatically activates voice recognition when you want to create a new chat. That saves at least one click. :)

Regarding the Assistants API, I don't yet have any concrete ideas on how to integrate it. Do you have any ideas? :)

**Comment by DevEmperor** [comment]
Hey, I just added the feature. You can now start the app via a complication that opens the input directly. :)

**Comment by DevEmperor** [comment]
I will push the update to the PlayStore today, then it will probably be out by Wednesday at the latest.

I haven't fully learnt about the assistants yet either. That's definitely next on the agenda. Your description sounds good, so I'll work my way through it until I've implemented it. :)

**Comment by muehlt** [comment]
Works good so far, thank you! I like the toggle to always have voice input directly.

**Comment by muehlt** [comment]
One enhancement related to the new input method would be to enable TTS conditionally depending on how the input was provided, since most of the time you'll want it to talk back if you talked (e.g. at home) or write back if you wrote (e.g. in the bus). I am not sure, but I assume it is provided how the input was given. Maybe we could change the TTS toggle to a selection of "Always on", "Always off", "On voice input" or something similar, but I'd give this feature a rather low priority, since pressing a message works well (although a better feedback could be provided there).

**Comment by DevEmperor** [comment]
Hey, I just changed the TTS settings to a list, where you can choose exactly the option that you suggested. :)
See 73efddf
