### ISSUE TITLE
How to use "Hands-free input"

### ISSUE THREAD

**Issue by metatrot** [DevEmperor/WristAssist#19]
There's an option called "hands-free input" in the app settings, but I don't see what enabling it changes. Is this a way to use the app without needing to manually start and stop STT recordings?

**Comment by DevEmperor** [comment]
Hey, with the "Hands-free input" option, if you want to create a new chat, the dictation function of the installed keyboard is activated directly. However, I have only tested this with the Samsung keyboard and the Gboard from Google. Then you no longer have to click on the microphone icon to record the prompt.
