### ISSUE TITLE
Buisness of WristAssist, make millions out of it

### ISSUE THREAD

**Issue by AnshuMishra01** [DevEmperor/WristAssist#8]
Hi I am Anshu Mishra, Currently running 2 startups in India and they are profitable, I am quite interested in doing one with you on WristAssist Application. Its quite unique and we can reach a good number of people if you take my business advices, I am ready to be your partner, You handle the tech and I the business, but first we need to talk so here's one of my Linkedin profile [Link](https://www.linkedin.com/in/anshu-mishra023129/) or you can mail me at - anshum.ug21.ee@nitp.ac.in

**Comment by DevEmperor** [comment]
Hello Anshu Mishra,
Unfortunately, I am not interested in turning the app into a business. The app serves as a hobby project for me as a student, which I would like to make available to others. Thank you for your request anyway. :)
